-- Load file
require('settings')
require('keymaps')
require('package_manager')
require('colorscheme')
require('snipping')
require('lsp')
require('winbar')
require('autocompletion')
require('syntax')
require('status_line')
require('file_manager')
require('color')
